name: Manual Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build Package
        run: mvn --batch-mode package
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: playit-minecraft-plugin.jar
          path: ./target/playit-minecraft-plugin.jar
